// Auto-generated by scripts/fetch-github-stats.mjs during `npm run build`.
// Do not edit by hand — this file is overwritten on every build with fresh
// counts from the GitHub API. If GitHub was unreachable at build time, the
// previously committed values below are kept as-is.
export const githubStats = {
  publicRepos: 7,
  liveInProduction: 3,
  updatedAt: "2026-09-15",
};
